[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_APP_ENV = "production"
  VITE_PROD_API_URL = "https://landify-be-production.up.railway.app"
  VITE_API_URL = "https://landify-be-production.up.railway.app"
  VITE_API_SERVER_URL = "https://landify-be-production.up.railway.app"

# Headers for API security
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 