import { Button } from '@/components/ui/button';
import { Download, Edit3, Eye, Menu, Share, X } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';

interface FloatingActionButtonProps {
  pageId: string;
  businessName: string;
  htmlContent?: string;
}

export function FloatingActionButton({ pageId, businessName, htmlContent }: FloatingActionButtonProps) {
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const navigate = useNavigate();
  const menuRef = useRef<HTMLDivElement>(null);

  const toggleMenu = () => {
    setIsMenuOpen(!isMenuOpen);
  };

  // Close menu when clicking outside
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (menuRef.current && !menuRef.current.contains(event.target as Node)) {
        setIsMenuOpen(false);
      }
    };

    if (isMenuOpen) {
      document.addEventListener('mousedown', handleClickOutside);
    }

    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, [isMenuOpen]);

  const handleEdit = () => {
    navigate(`/editor/${pageId}`);
    setIsMenuOpen(false);
  };

  const handleShare = () => {
    if (navigator.share) {
      navigator.share({
        title: `${businessName} - Landing Page`,
        text: `Check out the landing page for ${businessName}`,
        url: window.location.href
      });
    } else {
      // Fallback to copying URL to clipboard
      navigator.clipboard.writeText(window.location.href);
      // You could add a toast notification here
      alert('Page URL copied to clipboard!');
    }
    setIsMenuOpen(false);
  };

  const handleViewPages = () => {
    navigate('/pages');
    setIsMenuOpen(false);
  };

  const handleDownload = () => {
    try {
      // Use the provided HTML content directly instead of trying to extract from DOM
      const cleanedHTML = generateCleanHTML(htmlContent || '', businessName);

      // Create and trigger download
      const blob = new Blob([cleanedHTML], { type: 'text/html;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `${businessName.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_landing_page.html`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);

    } catch (error) {
      console.error('❌ Failed to download landing page:', error);
      // Fallback: copy content to clipboard
      if (navigator.clipboard && htmlContent) {
        navigator.clipboard.writeText(htmlContent).then(() => {
          alert('Download failed, but page HTML has been copied to clipboard!');
        });
      } else {
        alert('Download failed. Please try again or contact support.');
      }
    }
    setIsMenuOpen(false);
  };

  // Generate a clean, self-contained HTML file
  const generateCleanHTML = (originalHTML: string, businessName: string): string => {
    if (!originalHTML) {
      // Fallback HTML if no content provided
      return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${businessName} - Landing Page</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    <div class="min-h-screen flex items-center justify-center bg-gray-100">
        <div class="text-center">
            <h1 class="text-4xl font-bold text-gray-900 mb-4">${businessName}</h1>
            <p class="text-gray-600">Landing page content will be available after generation.</p>
        </div>
    </div>
</body>
</html>`;
    }

    // Return the HTML content as-is since it's already a complete HTML document
    // Just add the Landify footer if it doesn't already exist
    if (!originalHTML.includes('Landing page generated by Landify')) {
      const footerHTML = `
    <!-- Landify Footer -->
    <div style="text-align: center; padding: 2rem; background: #f8fafc; border-top: 1px solid #e2e8f0; margin-top: 4rem;">
        <p style="color: #64748b; font-size: 0.875rem; margin: 0;">
            Landing page generated by Landify • <a href="https://landify.ai" style="color: #3b82f6;">Visit Landify</a>
        </p>
    </div>`;

      return originalHTML.replace('</body>', `${footerHTML}\n</body>`);
    }

    return originalHTML;
  };

  return (
    <div ref={menuRef} className="fixed bottom-6 right-6 z-50" data-floating-button>
      {/* Menu Items */}
      {isMenuOpen && (
        <div className="absolute bottom-16 right-0 mb-4 space-y-3 animate-in slide-in-from-bottom duration-200">
          {/* Edit Button */}
          <div className="flex items-center justify-end space-x-3">
            <div className="bg-gray-900 text-white px-3 py-1 rounded-lg text-sm font-medium shadow-lg whitespace-nowrap opacity-90">
              Edit Page
            </div>
            <Button
              onClick={handleEdit}
              size="sm"
              aria-label="Edit this landing page"
              className="h-12 w-12 rounded-full bg-blue-500 hover:bg-blue-600 text-white shadow-lg hover:shadow-xl transition-all duration-200 flex items-center justify-center hover:scale-105"
            >
              <Edit3 className="h-5 w-5" />
            </Button>
          </div>

          {/* Share Button */}
          <div className="flex items-center justify-end space-x-3">
            <div className="bg-gray-900 text-white px-3 py-1 rounded-lg text-sm font-medium shadow-lg whitespace-nowrap opacity-90">
              Share Page
            </div>
            <Button
              onClick={handleShare}
              size="sm"
              aria-label="Share this landing page"
              className="h-12 w-12 rounded-full bg-green-500 hover:bg-green-600 text-white shadow-lg hover:shadow-xl transition-all duration-200 flex items-center justify-center hover:scale-105"
            >
              <Share className="h-5 w-5" />
            </Button>
          </div>

          {/* Download Button */}
          <div className="flex items-center justify-end space-x-3">
            <div className="bg-gray-900 text-white px-3 py-1 rounded-lg text-sm font-medium shadow-lg whitespace-nowrap opacity-90">
              Download HTML
            </div>
            <Button
              onClick={handleDownload}
              size="sm"
              aria-label="Download landing page as HTML file"
              className="h-12 w-12 rounded-full bg-orange-500 hover:bg-orange-600 text-white shadow-lg hover:shadow-xl transition-all duration-200 flex items-center justify-center hover:scale-105"
            >
              <Download className="h-5 w-5" />
            </Button>
          </div>

          {/* View All Pages */}
          <div className="flex items-center justify-end space-x-3">
            <div className="bg-gray-900 text-white px-3 py-1 rounded-lg text-sm font-medium shadow-lg whitespace-nowrap opacity-90">
              All Pages
            </div>
            <Button
              onClick={handleViewPages}
              size="sm"
              aria-label="View all landing pages"
              className="h-12 w-12 rounded-full bg-purple-500 hover:bg-purple-600 text-white shadow-lg hover:shadow-xl transition-all duration-200 flex items-center justify-center hover:scale-105"
            >
              <Eye className="h-5 w-5" />
            </Button>
          </div>
        </div>
      )}

      {/* Main FAB */}
      <Button
        onClick={toggleMenu}
        aria-label={isMenuOpen ? 'Close menu' : 'Open page options menu'}
        className={`h-14 w-14 rounded-full shadow-lg hover:shadow-xl transition-all duration-200 flex items-center justify-center hover:scale-105 ${isMenuOpen
          ? 'bg-red-500 hover:bg-red-600 rotate-180'
          : 'bg-indigo-500 hover:bg-indigo-600'
        } text-white`}
      >
        {isMenuOpen ? (
          <X className="h-6 w-6" />
        ) : (
          <Menu className="h-6 w-6" />
        )}
      </Button>

      {/* Backdrop for mobile */}
      {isMenuOpen && (
        <div
          className="fixed inset-0 bg-black bg-opacity-20 -z-10 md:hidden"
          onClick={() => setIsMenuOpen(false)}
        />
      )}
    </div>
  );
}

export default FloatingActionButton; 